import { FormEvent, useEffect, useState } from 'react'
import { json, request, requestPage } from './api'
import type { Role, User } from './types'
import { date, Empty, Modal, Pagination, short, Status } from './ui'
import { linkWallet } from './chain'

const PAGE_SIZE=10

export function UsersPage({current,notify}:{current:User;notify:(m:string,t?:'success'|'error')=>void}){
  const [users,setUsers]=useState<User[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[selected,setSelected]=useState<User|null>(null),[loading,setLoading]=useState(true)
  const load=()=>{setLoading(true);return requestPage<User[]>(`/users?limit=${PAGE_SIZE}&offset=${page*PAGE_SIZE}`).then(r=>{setUsers(r.data);setTotal(r.total)}).finally(()=>setLoading(false))}
  useEffect(()=>{load()},[page])
  const save=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);request<User>(`/users/${selected!.id}`,{...json({display_name:String(f.get('display_name')),role:selected!.id===current.id?selected!.role:String(f.get('role')) as Role,is_active:selected!.id===current.id?selected!.is_active:f.get('is_active')==='true'}),method:'PUT'}).then(()=>{notify('用户信息已更新');setSelected(null);load()}).catch(e=>notify(e.message,'error'))}
  return <><section className="page-intro"><div><span className="eyebrow">ACCESS CONTROL</span><h2>用户与角色管理</h2><p>管理账号名称、角色和启用状态。</p></div></section>
    <div className="card table-card">{loading?<div className="loading"><span/><span/><span/></div>:users.length?<><div className="table-wrap"><table><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>创建时间</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.display_name}</strong><small>{u.email} · {short(u.id)}</small></td><td>{{admin:'管理员',verifier:'核证员',member:'企业用户'}[u.role]}</td><td><Status value={u.is_active?'confirmed':'failed'}/></td><td>{u.created_at?date(u.created_at):'—'}</td><td><div className="row-actions"><button onClick={()=>setSelected(u)}>管理</button></div></td></tr>)}</tbody></table></div><Pagination page={page} total={total} pageSize={PAGE_SIZE} onChange={setPage}/></>:<Empty title="暂无用户"/>}</div>
    {selected&&<Modal title={`管理 · ${selected.display_name}`} onClose={()=>setSelected(null)}><form className="form-grid" onSubmit={save}><label className="full">显示名称<input name="display_name" defaultValue={selected.display_name} required/></label><label>角色<select name="role" defaultValue={selected.role} disabled={selected.id===current.id}><option value="member">企业用户</option><option value="verifier">核证员</option><option value="admin">管理员</option></select></label><label>账号状态<select name="is_active" defaultValue={String(selected.is_active)} disabled={selected.id===current.id}><option value="true">启用</option><option value="false">停用</option></select></label><div className="form-actions full"><button type="button" className="btn btn-ghost" onClick={()=>setSelected(null)}>取消</button><button className="btn btn-primary">保存</button></div></form></Modal>}
  </>
}

export function AccountPage({user,notify}:{user:User;notify:(m:string,t?:'success'|'error')=>void}){
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);const next=String(f.get('new_password')),confirm=String(f.get('confirm_password'));if(next!==confirm){notify('两次输入的新密码不一致','error');return}request('/users/me/password',json({current_password:String(f.get('current_password')),new_password:next})).then(()=>{notify('密码已修改，请重新登录');form.reset();localStorage.removeItem('carbonlink_token');window.dispatchEvent(new Event('carbonlink:unauthorized'))}).catch(e=>notify(e.message,'error'))}
  const connect=()=>linkWallet(user).then(()=>{notify('钱包地址已通过签名验证并绑定');setTimeout(()=>location.reload(),500)}).catch(e=>notify(e.message,'error'))
  return <><section className="page-intro"><div><span className="eyebrow">MY ACCOUNT</span><h2>账号设置</h2><p>管理登录安全和自托管钱包。</p></div></section><div className="account-grid"><div className="card"><div className="card-head"><div><span className="eyebrow">SELF-CUSTODY</span><h3>链上钱包</h3></div></div><p><strong>{user.display_name}</strong></p><p className="muted">{user.email}</p><p className="muted">{user.wallet_address?`已绑定：${user.wallet_address}`:'尚未绑定钱包；项目获批前必须完成绑定。'}</p><button className="btn btn-primary" onClick={connect}>{user.wallet_address?'重新验证钱包':'连接并绑定钱包'}</button><p className="muted">平台不会创建、保存或接触您的私钥。绑定和链上操作均由钱包签名。</p></div><div className="card"><div className="card-head"><div><span className="eyebrow">SECURITY</span><h3>修改密码</h3></div></div><form className="form-grid" onSubmit={submit}><label className="full">当前密码<input name="current_password" type="password" required/></label><label className="full">新密码<input name="new_password" type="password" minLength={10} required/></label><label className="full">确认新密码<input name="confirm_password" type="password" minLength={10} required/></label><div className="form-actions full"><button className="btn btn-primary">更新密码</button></div></form></div></div></>
}
