import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { json, request, uploadDocument } from './api'
import type { AgentDraft, AgentReply, ApplicationReadiness, Project, ProjectDocument, User } from './types'
import { fmt, Icon, Modal, Status } from './ui'

const requirements=[
  {key:'project_design',title:'项目设计文件（PDD）',hint:'项目边界、活动内容、减排机制与实施计划'},
  {key:'ownership',title:'项目权属或授权证明',hint:'营业执照、资产权属、合作或授权文件'},
  {key:'methodology',title:'方法学适用性说明',hint:'适用条件论证、额外性说明与计算依据'},
  {key:'monitoring',title:'监测计划与基线数据',hint:'监测参数、数据来源、频次与质量控制'},
]
const initialReadiness:ApplicationReadiness={ready:false,completed_categories:[],missing_categories:requirements.map(x=>x.key),completion_percent:0}

type ChatMessage={from:'agent'|'user';text:string}
const draftLabels:Record<string,string>={name:'项目名称',project_type:'项目类型',region:'所在地区',methodology:'方法学',estimated_tonnes:'预计减排量（tCO₂e）',description:'项目说明'}
const typeLabels:Record<string,string>={renewable_energy:'可再生能源',forestry:'林业碳汇',energy_efficiency:'节能提效',methane_recovery:'甲烷回收'}
type Conversation={chat:ChatMessage[];draft:AgentDraft;stage:string;actions:string[];modelAvailable?:boolean}
const emptyConversation=():Conversation=>({chat:[],draft:{},stage:'',actions:[]})

export function ApplicationPage({user,notify}:{user:User;notify:(m:string,t?:'success'|'error')=>void}){
  const [projects,setProjects]=useState<Project[]>([]),[selectedId,setSelectedId]=useState(''),[documents,setDocuments]=useState<ProjectDocument[]>([])
  const [readiness,setReadiness]=useState(initialReadiness),[loading,setLoading]=useState(true),[createOpen,setCreateOpen]=useState(false),[uploading,setUploading]=useState(''),[materialsOpen,setMaterialsOpen]=useState(false),[detailsLoading,setDetailsLoading]=useState(false)
  const [message,setMessage]=useState(''),[asking,setAsking]=useState(false),[saving,setSaving]=useState(false)
  const [conversations,setConversations]=useState<Record<string,Conversation>>({})
  const key=selectedId||'new', conversation=conversations[key]||emptyConversation(),chat=conversation.chat
  const chatEnd=useRef<HTMLDivElement>(null),busy=useRef(false)
  const selected=useMemo(()=>projects.find(p=>p.id===selectedId),[projects,selectedId])
  const selectedRef=useRef(selectedId)
  selectedRef.current=selectedId
  const canEdit=selected?.status==='draft'||selected?.status==='rejected'
  const loadProjects=async()=>{setLoading(true);try{setProjects(await request<Project[]>('/projects?mine=true&limit=100'))}catch(e){notify(e instanceof Error?e.message:'项目读取失败','error')}finally{setLoading(false)}}
  const loadApplication=async()=>{if(!selectedId)return;const [docs,ready]=await Promise.all([request<ProjectDocument[]>(`/projects/${selectedId}/documents`),request<ApplicationReadiness>(`/applications/${selectedId}/readiness`)]);if(selectedRef.current===selectedId){setDocuments(docs);setReadiness(ready)}}
  useEffect(()=>{void loadProjects()},[])
  useEffect(()=>{let active=true;setDocuments([]);setReadiness(initialReadiness);if(!selectedId){setDetailsLoading(false);return}setDetailsLoading(true);Promise.all([request<ProjectDocument[]>(`/projects/${selectedId}/documents`),request<ApplicationReadiness>(`/applications/${selectedId}/readiness`)]).then(([docs,ready])=>{if(active){setDocuments(docs);setReadiness(ready)}}).catch(e=>{if(active)notify(e.message,'error')}).finally(()=>{if(active)setDetailsLoading(false)});return()=>{active=false}},[selectedId])
  useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'})},[chat.length,asking])
  const switchProject=(id:string)=>{if(busy.current||saving||uploading)return;setSelectedId(id);setMessage('');setMaterialsOpen(false)}
  const saveProject=async(draft:AgentDraft)=>{if(busy.current)return;busy.current=true;setSaving(true);try{const p=await request<Project>('/projects',json(draft));setProjects(old=>[p,...old]);setSelectedId(p.id);setConversations(old=>({...old,new:emptyConversation(),[p.id]:{...emptyConversation(),chat:[{from:'agent',text:`“${p.name}”已创建。接下来我会陪你准备审核材料，可以问我需要哪些文件，或打开右侧材料面板。`}]}}));setCreateOpen(false);notify('项目档案已创建')}catch(e){notify(e instanceof Error?e.message:'创建失败','error')}finally{busy.current=false;setSaving(false)}}
  const create=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void saveProject(Object.fromEntries(f.entries()) as AgentDraft)}
  const upload=async(category:string,file?:File)=>{if(!selected||!file)return;setUploading(category);try{await uploadDocument(selected.id,category,file);notify('材料上传成功');await loadApplication()}catch(e){notify(e instanceof Error?e.message:'上传失败','error')}finally{setUploading('')}}
  const remove=async(doc:ProjectDocument)=>{if(!selected||!confirm(`移除“${doc.original_name}”？`))return;try{await request(`/projects/${selected.id}/documents/${doc.id}`,{method:'DELETE'});await loadApplication();notify('材料已移除')}catch(e){notify(e instanceof Error?e.message:'移除失败','error')}}
  const submit=async()=>{if(!selected||saving)return;setSaving(true);try{const p=await request<Project>(`/applications/${selected.id}/submit`,{method:'POST'});setProjects(old=>old.map(item=>item.id===p.id?p:item));notify('项目已提交平台审核')}catch(e){notify(e instanceof Error?e.message:'提交失败','error')}finally{setSaving(false)}}
  const ask=async(text=message)=>{const value=text.trim();if(!value||busy.current||saving)return;busy.current=true;const next:ChatMessage[]=[...chat,{from:'user',text:value}];setConversations(old=>({...old,[key]:{...conversation,chat:next}}));setMessage('');setAsking(true);try{const answer=await request<AgentReply>('/application-agent/message',json({project_id:selectedId||null,message:value,draft:conversation.draft,history:chat.slice(-30).map(m=>({role:m.from==='user'?'user':'assistant',content:m.text.slice(0,4000)}))}));setConversations(old=>({...old,[key]:{chat:[...next,{from:'agent',text:answer.reply}],draft:answer.draft||{},stage:answer.stage,actions:answer.suggested_actions,modelAvailable:answer.model_available}}));if(answer.readiness)setReadiness(answer.readiness)}catch(e){setConversations(old=>({...old,[key]:{...conversation,chat:[...next,{from:'agent',text:e instanceof Error?e.message:'助手暂时无法响应，请重试。'}]}}))}finally{busy.current=false;setAsking(false)}}
  const prompts=selected?['查看项目概况','我还缺哪些材料？','如何准备方法学说明？']:['我想新建一个减排项目','新项目需要提供哪些信息？']
  return <div className="copilot-workspace">
    <div className="copilot-atmosphere" aria-hidden="true"><div className="copilot-grid"/><i/><i/><i/><div className="copilot-orbit"/></div>
    <header className="copilot-title"><div><span className="eyebrow">CARBONLINK / INTELLIGENT WORKSPACE</span><h2>从一个想法，到一份可信申报。</h2><p>和 Carbon Copilot 聊聊你的项目，让申报自然发生。</p></div><span className="copilot-tag"><i/> AGENT WORKSPACE</span></header>
    <div className="copilot-layout">
      <main className="copilot-chat">
        <header className="copilot-chat-header"><span className="agent-avatar"><Icon name="spark"/></span><div><b>Carbon Copilot</b><small>{selected?`正在协助 · ${selected.name}`:'新项目 · 对话式建档'}</small></div><span className="copilot-mode">{asking?'正在处理…':'申报 Agent'}</span></header>
        <div className="copilot-stream" role="log" aria-live="polite" aria-label="项目申报对话">
          {!chat.length&&<div className="copilot-welcome"><div className="copilot-emblem"><Icon name="spark" size={36}/></div><span className="eyebrow">YOUR CARBON COPILOT</span><h3>{selected?'项目已就位，想了解些什么？':`${user.display_name}，一起开启低碳新项目。`}</h3><p>{selected?'我会结合项目档案、材料清单和审核反馈回答你的问题。':'描述你的项目，我会整理关键信息、追问缺项，并在你确认后创建档案。'}</p><div className="copilot-starters">{prompts.map((text,i)=><button key={text} onClick={()=>ask(text)}><Icon name={i?'file':'plus'} size={20}/><b>{text}</b><Icon name="arrow" size={15}/></button>)}</div><small>例如：我们想在深圳的厂房屋顶装光伏，每年预计减排约一万吨，还不清楚用哪种方法学。</small></div>}
          {chat.map((m,i)=><div className={`copilot-message ${m.from}`} key={i}><span className="copilot-speaker">{m.from==='agent'?<Icon name="spark" size={16}/>:user.display_name.slice(0,1)}</span><div><small>{m.from==='agent'?'Carbon Copilot':'你'}</small><div className="copilot-bubble">{m.text}</div></div></div>)}
          {!selected&&Object.keys(conversation.draft).length>0&&<section className="copilot-draft"><header><Icon name="project" size={18}/><b>自动整理的申报表单</b><span>{conversation.stage==='confirm_project'?'待你确认':'随对话自动填写'}</span></header><dl>{Object.entries(draftLabels).map(([field,label])=>{const value=conversation.draft[field as keyof AgentDraft];return <div key={field}><dt>{label}</dt><dd className={!value?'copilot-field-missing':''}>{value?(typeLabels[value]||value):'待补充'}</dd></div>})}</dl>{conversation.stage==='confirm_project'&&<button className="btn portal-primary" disabled={saving||asking} onClick={()=>saveProject(conversation.draft)}>{saving?'正在创建…':'确认创建项目'}<Icon name="arrow" size={16}/></button>}<button className="copilot-text-button" disabled={asking||saving} onClick={()=>setCreateOpen(true)}>查看并修改表单</button></section>}
          {asking&&<div className="copilot-thinking"><span className="typing"><i/><i/><i/></span> 正在整理项目信息…</div>}<div ref={chatEnd}/>
        </div>
        <div className="copilot-composer-wrap">{!!chat.length&&<div className="copilot-suggestions">{(conversation.actions.length?conversation.actions:prompts).map(text=><button disabled={asking||saving} key={text} onClick={()=>ask(text)}>{text}</button>)}</div>}
          <form className="copilot-composer" onSubmit={e=>{e.preventDefault();ask()}}><label className="sr-only" htmlFor="copilot-message">向申报 Agent 发送消息</label><textarea id="copilot-message" value={message} maxLength={4000} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();ask()}}} placeholder={selected?'询问项目进度、材料要求或审核反馈…':'描述你的项目，或告诉我你想从哪里开始…'} rows={3}/><div><span><Icon name="chain" size={13}/>{selected?'已关联项目档案':'对话引导 · 确认后建档'}</span><button aria-label="发送消息" disabled={!message.trim()||asking||saving}><Icon name="send" size={18}/></button></div></form><footer>{conversation.modelAvailable===false?(selected?'当前使用基础引导模式，回答基于项目档案与材料清单。':'智能对话暂时不可用，可稍后重试或打开辅助表单。'):'Enter 发送 · Shift + Enter 换行'}<span>AI 建议供参考，最终以平台审核为准</span></footer>
        </div>
      </main>
      <aside className="copilot-context"><section><span className="eyebrow">PROJECT CONTEXT</span><h3>你的项目空间</h3><button className={`copilot-new ${!selectedId?'active':''}`} disabled={asking||saving||!!uploading} onClick={()=>switchProject('')}><Icon name="plus" size={18}/>通过对话新建项目</button><label className="copilot-select">切换已有项目<select value={selectedId} disabled={asking||saving||!!uploading||loading} onChange={e=>switchProject(e.target.value)}><option value="">{loading?'正在读取项目…':'新项目对话'}</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{selected?<div className="copilot-project-summary"><Status value={selected.status}/><h4>{selected.name}</h4><p>{selected.region} · {typeLabels[selected.project_type]||selected.project_type}</p><strong>{fmt(selected.estimated_tonnes,0)}<small> tCO₂e</small></strong><span>预计减排量</span></div>:<p className="copilot-context-hint">一个对话，推进一份申报。<br/>也可以选择已有项目，继续跟进。</p>}</section>
        <section><span className="eyebrow">APPLICATION JOURNEY</span><h3>申报路径</h3><ol className="copilot-steps"><li className={!selected?'current':'done'}><span>01</span><div><b>聊一聊项目</b><small>整理信息，确认创建档案</small></div></li><li className={selected&&canEdit?'current':''}><span>02</span><div><b>准备审核材料</b><small>{selected?detailsLoading?'正在读取材料…':`${readiness.completed_categories.length} / 4 项材料已上传`:'由助手引导逐项准备'}</small></div></li><li className={selected&&!canEdit?'current':''}><span>03</span><div><b>提交平台审核</b><small>核验资料，跟进审核结果</small></div></li></ol>{selected&&<button className="copilot-material-button" disabled={detailsLoading} onClick={()=>setMaterialsOpen(true)}><Icon name="file" size={16}/>查看档案与材料<Icon name="arrow" size={14}/></button>}</section>
        <div className="copilot-form-entry"><Icon name="audit" size={17}/><div><b>习惯自己填写？</b><button disabled={asking||saving} onClick={()=>setCreateOpen(true)}>使用辅助表单新建项目 <span>↗</span></button></div></div>
      </aside>
    </div>
    {materialsOpen&&<Modal title="项目档案与审核材料" onClose={()=>{if(!uploading)setMaterialsOpen(false)}}><div className="copilot-materials">        {selected&&<><section className="project-overview-strip"><div><span>项目类型</span><b>{typeLabels[selected.project_type]||selected.project_type}</b></div><div><span>所在地区</span><b>{selected.region}</b></div><div><span>采用方法学</span><b>{selected.methodology}</b></div><div><span>预计减排量</span><b>{fmt(selected.estimated_tonnes,0)} <small>tCO₂e</small></b></div></section>
        <section className="portal-section"><div className="section-heading"><div><span className="eyebrow">REVIEW MATERIALS</span><h3>审核材料</h3><p>以下 4 项为提交平台审核的必要材料</p></div><div className="completion-pill"><i style={{width:`${readiness.completion_percent}%`}}/><span>{readiness.completed_categories.length} / {requirements.length} 已完成</span></div></div>
          <div className="material-list">{requirements.map((item,index)=>{const docs=documents.filter(d=>d.category===item.key),done=docs.length>0;return <article className={`material-row ${done?'done':''}`} key={item.key}><div className="material-index">{done?<Icon name="check" size={17}/>:String(index+1).padStart(2,'0')}</div><div className="material-copy"><b>{item.title}</b><p>{item.hint}</p>{docs.map(doc=><div className="uploaded-file" key={doc.id}><Icon name="file" size={15}/><span>{doc.original_name}</span><small>{(doc.size_bytes/1024/1024).toFixed(1)} MB</small>{canEdit&&<button onClick={()=>remove(doc)}>移除</button>}</div>)}</div><label className={`upload-action ${!canEdit?'disabled':''}`}><Icon name="upload" size={16}/>{uploading===item.key?'上传中…':done?'补充材料':'上传材料'}<input aria-label={`上传${item.title}`} type="file" disabled={!canEdit||!!uploading} accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" onChange={e=>{upload(item.key,e.target.files?.[0]);e.currentTarget.value=''}}/></label></article>})}</div>
          {selected.review_note&&<div className="review-feedback"><Icon name="audit"/><div><b>审核反馈</b><p>{selected.review_note}</p></div></div>}
          <div className="submission-bar"><div><span className={`readiness-dot ${readiness.ready?'ready':''}`}/><div><b>{readiness.ready?'所有必需材料已齐备':'材料尚未齐备'}</b><small>{readiness.ready?'提交后平台核证人员将开始审核':'请完成缺失项目后再提交'}</small></div></div><button className="btn portal-primary" disabled={!readiness.ready||!canEdit||saving||detailsLoading} onClick={submit}>提交平台审核 <Icon name="arrow" size={16}/></button></div>
        </section></>}
</div></Modal>}
    {createOpen&&<Modal title="创建企业项目档案" onClose={()=>setCreateOpen(false)}><form className="form-grid" onSubmit={create}><div className="form-note full">对话中已确认的信息会自动填入，你可以在这里核对、补充或修改。</div><label className="full">项目名称<input defaultValue={conversation.draft.name} name="name" required minLength={2} maxLength={200} placeholder="例如：华南分布式光伏一期" autoFocus/></label><label>项目类型<select defaultValue={conversation.draft.project_type} name="project_type"><option value="renewable_energy">可再生能源</option><option value="forestry">林业碳汇</option><option value="energy_efficiency">节能提效</option><option value="methane_recovery">甲烷回收</option></select></label><label>所在地区<input defaultValue={conversation.draft.region} name="region" required minLength={2} maxLength={120} placeholder="省 / 市"/></label><label>核证方法学<input defaultValue={conversation.draft.methodology} name="methodology" required minLength={2} maxLength={120} placeholder="例如 CM-001-V01"/></label><label>预计减排量（tCO₂e）<input defaultValue={conversation.draft.estimated_tonnes} name="estimated_tonnes" type="number" min="0.0001" step="0.0001" required/></label><label className="full">项目说明<textarea defaultValue={conversation.draft.description} name="description" rows={4} maxLength={5000} required placeholder="说明项目范围、技术路线、建设周期及预期环境效益"/></label><div className="form-actions full"><button type="button" className="btn btn-ghost" onClick={()=>setCreateOpen(false)}>取消</button><button disabled={saving} className="btn btn-primary">{saving?'创建中…':'创建并继续'}</button></div></form></Modal>}

  </div>
}
