import { FormEvent, useEffect, useMemo, useState } from 'react'
import { downloadDocument, idempotencyKey, json, request, requestPage } from './api'
import type { AuditEvent, Batch, BlockchainConfig, ChainOperation, Dashboard, Holding, Ledger, Listing, Project, ProjectDocument, Retirement, User } from './types'
import { date, Empty, fmt, Icon, Modal, Pagination, short, Status } from './ui'
import { creditAmount, wallet } from './chain'
import { keccak256, toUtf8Bytes } from 'ethers'
import type { ChainConfig } from './types'

const PAGE_SIZE=10

const useLoad = <T,>(loader:()=>Promise<T>, initial:T, deps:unknown[]=[]):[T,boolean,()=>Promise<void>] => {
  const [data,setData]=useState<T>(initial),[loading,setLoading]=useState(true)
  const load=async()=>{setLoading(true);try{setData(await loader())}finally{setLoading(false)}}
  useEffect(()=>{load()},deps)
  return [data,loading,load]
}
const Loader=()=> <div className="loading"><span/><span/><span/></div>
const field=(form:FormData,name:string)=>String(form.get(name)||'')

export function DashboardPage({user}:{user:User}){
  const [stats,loading]=useLoad(()=>request<Dashboard>('/dashboard'),{total_issued:'0',total_retired:'0',open_market_quantity:'0',trade_volume:'0',project_count:0})
  const [projects]=useLoad(()=>request<Project[]>('/projects?limit=5'),[])
  const [listings]=useLoad(()=>request<Listing[]>('/market/listings?limit=5'),[])
  const retirementRate=Number(stats.total_issued)?Number(stats.total_retired)/Number(stats.total_issued)*100:0
  if(loading)return <Loader/>
  return <>
    <section className="welcome-row"><div><span className="eyebrow">{new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span><h2>你好，{user.display_name}</h2><p>这里是碳资产运营的实时概览。</p></div><div className="trust-chip"><span className="trust-icon"><Icon name="check"/></span><div><b>数据服务正常</b><small>账本与链上队列运行中</small></div></div></section>
    <section className="metric-grid">
      <Metric label="累计签发" value={fmt(stats.total_issued)} unit="tCO₂e" tone="green" trend="平台已核证资产"/>
      <Metric label="累计注销" value={fmt(stats.total_retired)} unit="tCO₂e" tone="sand" trend={`${retirementRate.toFixed(1)}% 注销率`}/>
      <Metric label="市场在售" value={fmt(stats.open_market_quantity)} unit="tCO₂e" tone="blue" trend="当前可交易额度"/>
      <Metric label="累计成交" value={fmt(stats.trade_volume)} unit="tCO₂e" tone="ink" trend={`${stats.project_count} 个登记项目`}/>
    </section>
    <section className="dashboard-grid">
      <div className="card span-2"><div className="card-head"><div><span className="eyebrow">项目进度</span><h3>最近登记项目</h3></div><a href="/projects" className="text-link">查看全部 <Icon name="arrow" size={16}/></a></div>
        {projects.length?<div className="project-list">{projects.map(p=><div className="project-row" key={p.id}><div className="project-symbol"><Icon name="project"/></div><div className="project-info"><strong>{p.name}</strong><span>{p.region} · {p.methodology}</span></div><div className="project-tonnes"><b>{fmt(p.estimated_tonnes,0)}</b><span>预计吨数</span></div><Status value={p.status}/></div>)}</div>:<Empty title="暂无项目" text="创建首个碳项目后，进度会显示在这里。"/>}
      </div>
      <div className="card impact-card"><span className="eyebrow light">碳影响力</span><h3>{fmt(stats.total_retired,0)}</h3><p>吨二氧化碳当量已永久注销</p><div className="impact-ring"><span>{retirementRate.toFixed(0)}%</span><small>注销率</small></div><div className="leaf-art"><Icon name="leaf" size={94}/></div></div>
      <div className="card span-3"><div className="card-head"><div><span className="eyebrow">实时市场</span><h3>最新在售资产</h3></div><a href="/market" className="text-link">进入市场 <Icon name="arrow" size={16}/></a></div>
        {listings.length?<div className="market-strip">{listings.slice(0,4).map(l=><div key={l.id}><span>{short(l.batch_id,6)}</span><strong>{fmt(l.remaining_quantity)} t</strong><b>¥ {fmt(l.unit_price)} / t</b></div>)}</div>:<Empty title="暂无在售资产" text="市场挂单将显示在这里。"/>}
      </div>
    </section>
  </>
}

function Metric({label,value,unit,tone,trend}:{label:string;value:string;unit:string;tone:string;trend:string}){return <div className={`metric-card ${tone}`}><div className="metric-top"><span>{label}</span><i/></div><strong>{value}</strong><small>{unit}</small><footer>{trend}</footer></div>}

export function ProjectsPage({user,notify}:{user:User;notify:(m:string,t?:'success'|'error')=>void}){
  const [filter,setFilter]=useState(''),[page,setPage]=useState(0),[modal,setModal]=useState<'create'|'edit'|'review'|'issue'|null>(null),[selected,setSelected]=useState<Project|null>(null)
  const [reviewDocuments,setReviewDocuments]=useState<ProjectDocument[]>([])
  const [result,loading,reload]=useLoad(()=>requestPage<Project[]>(`/projects?limit=${PAGE_SIZE}&offset=${page*PAGE_SIZE}${filter?`&status=${filter}`:''}`),{data:[],total:0},[filter,page]),projects=result.data
  const privileged=user.role==='admin'||user.role==='verifier'
  const action=async(fn:()=>Promise<unknown>,message:string)=>{try{await fn();notify(message);setModal(null);reload()}catch(e){notify(e instanceof Error?e.message:'操作失败','error')}}
  const create=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);action(()=>request('/projects',json({name:field(f,'name'),project_type:field(f,'project_type'),region:field(f,'region'),methodology:field(f,'methodology'),description:field(f,'description'),estimated_tonnes:field(f,'estimated_tonnes')})),'项目已创建')}
  const edit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);action(()=>request(`/projects/${selected!.id}`,{...json({name:field(f,'name'),project_type:field(f,'project_type'),region:field(f,'region'),methodology:field(f,'methodology'),description:field(f,'description'),estimated_tonnes:field(f,'estimated_tonnes')}),method:'PUT'}),'项目已更新')}
  const remove=(p:Project)=>{if(window.confirm(`确认删除项目“${p.name}”？此操作不可撤销。`))action(()=>request(`/projects/${p.id}`,{method:'DELETE'}),'项目已删除')}
  const review=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);action(()=>request(`/projects/${selected!.id}/review`,json({approved:field(f,'decision')==='true',note:field(f,'note')})),'审核结果已保存')}
  const issue=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);action(()=>request('/credits/issue',{...json({project_id:selected!.id,vintage:Number(field(f,'vintage')),quantity:field(f,'quantity')}),headers:{'Idempotency-Key':idempotencyKey()}}),'碳额度已签发')}
  const openReview=async(p:Project)=>{setSelected(p);setReviewDocuments([]);setModal('review');try{setReviewDocuments(await request<ProjectDocument[]>(`/projects/${p.id}/documents`))}catch(e){notify(e instanceof Error?e.message:'读取材料失败','error')}}
  return <>
    <PageIntro eyebrow="PROJECT REGISTRY" title="碳项目全生命周期" text="登记、提交并核证减排项目，为碳额度签发建立可信基础。"><button className="btn btn-primary" onClick={()=>setModal('create')}><Icon name="plus"/>新建项目</button></PageIntro>
    <div className="toolbar"><div className="tabs">{[['','全部'],['draft','草稿'],['pending','待审核'],['approved','已通过'],['rejected','已驳回']].map(([v,l])=><button className={filter===v?'active':''} onClick={()=>{setFilter(v);setPage(0)}} key={v}>{l}</button>)}</div><span className="result-count">共 {result.total} 个项目</span></div>
    <div className="card table-card">{loading?<Loader/>:projects.length?<><div className="table-wrap"><table><thead><tr><th>项目</th><th>地区 / 类型</th><th>方法学</th><th>预计减排</th><th>状态</th><th>创建时间</th><th/></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><div className="primary-cell"><span className="table-icon"><Icon name="project"/></span><div><strong>{p.name}</strong><small>{short(p.id)}</small></div></div></td><td><strong>{p.region}</strong><small>{p.project_type}</small></td><td>{p.methodology}</td><td><strong>{fmt(p.estimated_tonnes)} t</strong></td><td><Status value={p.status}/></td><td>{date(p.created_at)}</td><td><div className="row-actions">{p.owner_id===user.id&&(p.status==='draft'||p.status==='rejected')&&<><button onClick={()=>{setSelected(p);setModal('edit')}}>编辑</button><button onClick={()=>action(()=>request(`/projects/${p.id}/submit`,{method:'POST'}),'项目已提交审核')}>提交</button><button className="danger-btn" onClick={()=>remove(p)}>删除</button></>}{privileged&&p.status==='pending'&&<button onClick={()=>openReview(p)}>审核</button>}{privileged&&p.status==='approved'&&<button onClick={()=>{setSelected(p);setModal('issue')}}>签发</button>}</div></td></tr>)}</tbody></table></div><Pagination page={page} total={result.total} pageSize={PAGE_SIZE} onChange={setPage}/></>:<Empty title="没有匹配的项目" text="调整筛选条件，或创建一个新的碳项目。"/>}</div>
    {modal==='create'&&<Modal title="登记新碳项目" onClose={()=>setModal(null)}><form className="form-grid" onSubmit={create}><label className="full">项目名称<input name="name" required placeholder="例如：华南光伏一期"/></label><label>项目类型<select name="project_type"><option value="renewable_energy">可再生能源</option><option value="forestry">林业碳汇</option><option value="energy_efficiency">节能提效</option><option value="methane_recovery">甲烷回收</option></select></label><label>所在地区<input name="region" required placeholder="广东"/></label><label>核证方法学<input name="methodology" required placeholder="CM-001-V01"/></label><label>预计减排量（tCO₂e）<input name="estimated_tonnes" type="number" step="0.0001" min="0.0001" required/></label><label className="full">项目说明<textarea name="description" rows={4} placeholder="简要描述项目范围、技术路线与预期影响"/></label><FormActions close={()=>setModal(null)} submit="创建项目"/></form></Modal>}
    {modal==='edit'&&selected&&<Modal title={`编辑 · ${selected.name}`} onClose={()=>setModal(null)}><form className="form-grid" onSubmit={edit}><label className="full">项目名称<input name="name" required defaultValue={selected.name}/></label><label>项目类型<select name="project_type" defaultValue={selected.project_type}><option value="renewable_energy">可再生能源</option><option value="forestry">林业碳汇</option><option value="energy_efficiency">节能提效</option><option value="methane_recovery">甲烷回收</option></select></label><label>所在地区<input name="region" required defaultValue={selected.region}/></label><label>核证方法学<input name="methodology" required defaultValue={selected.methodology}/></label><label>预计减排量（tCO₂e）<input name="estimated_tonnes" type="number" step="0.0001" min="0.0001" required defaultValue={selected.estimated_tonnes}/></label><label className="full">项目说明<textarea name="description" rows={4} defaultValue={selected.description}/></label><FormActions close={()=>setModal(null)} submit="保存修改"/></form></Modal>}
    {modal==='review'&&<Modal title={`审核 · ${selected?.name}`} onClose={()=>setModal(null)}><form className="form-grid" onSubmit={review}><div className="review-documents full"><span>企业提交材料</span>{reviewDocuments.length?reviewDocuments.map(d=><button type="button" key={d.id} onClick={()=>downloadDocument(selected!.id,d.id,d.original_name).catch(e=>notify(e.message,'error'))}><Icon name="file" size={15}/><b>{d.original_name}</b><small>{d.category} · {(d.size_bytes/1024/1024).toFixed(1)} MB</small></button>):<p>该项目通过旧流程提交，暂无关联材料。</p>}</div><label className="full">审核结论<select name="decision"><option value="true">核证通过</option><option value="false">驳回并要求补充材料</option></select></label><label className="full">审核意见<textarea name="note" required rows={4} placeholder="记录核证依据与意见"/></label><FormActions close={()=>setModal(null)} submit="确认审核"/></form></Modal>}
    {modal==='issue'&&<Modal title={`签发额度 · ${selected?.name}`} onClose={()=>setModal(null)}><form className="form-grid" onSubmit={issue}><div className="form-note full">签发交易由审批操作账户提交，额度直接进入项目所有人已验证的钱包。</div><label>核证年份<input name="vintage" type="number" min="1990" max="2100" defaultValue={new Date().getFullYear()} required/></label><label>签发数量（tCO₂e）<input name="quantity" type="number" min="0.0001" step="0.0001" required/></label><FormActions close={()=>setModal(null)} submit="确认签发"/></form></Modal>}
  </>
}

export function WalletPage({notify}:{notify:(m:string,t?:'success'|'error')=>void}){
  const [ledgerPage,setLedgerPage]=useState(0)
  const [holdings,loading]=useLoad(()=>request<Holding[]>('/wallet/holdings'),[]),[batches]=useLoad(()=>request<Batch[]>('/credits/batches?limit=100'),[]),[ledgerResult]=useLoad(()=>requestPage<Ledger[]>(`/wallet/ledger?limit=${PAGE_SIZE}&offset=${ledgerPage*PAGE_SIZE}`),{data:[],total:0},[ledgerPage]),ledger=ledgerResult.data
  const batchMap=useMemo(()=>Object.fromEntries(batches.map(b=>[b.id,b])),[batches]), total=holdings.reduce((s,h)=>s+Number(h.quantity),0), locked=holdings.reduce((s,h)=>s+Number(h.locked_quantity),0)
  const copy=(v:string)=>navigator.clipboard.writeText(v).then(()=>notify('批次编号已复制'))
  return <><PageIntro eyebrow="SELF-CUSTODY WALLET" title="我的链上碳资产" text="余额来自已绑定钱包；平台无法代签、转移或冻结您的个人资产。"/>
    <section className="wallet-summary"><div><span>资产总量</span><strong>{fmt(total)}</strong><small>tCO₂e</small></div><div><span>可用余额</span><strong>{fmt(total-locked)}</strong><small>tCO₂e</small></div><div><span>挂单锁定</span><strong>{fmt(locked)}</strong><small>tCO₂e</small></div></section>
    <section className="two-column"><div className="card"><div className="card-head"><div><span className="eyebrow">PORTFOLIO</span><h3>资产持仓</h3></div></div>{loading?<Loader/>:holdings.length?<div className="holding-list">{holdings.map(h=>{const b=batchMap[h.batch_id];return <div className="holding-card" key={h.batch_id}><div className="batch-seal"><Icon name="leaf"/></div><div className="holding-main"><span>{b?`${b.vintage} · ${b.methodology}`:'碳额度批次'}</span><strong>{fmt(h.quantity)} <small>tCO₂e</small></strong><button className="copy-id" onClick={()=>copy(h.batch_id)}>{short(h.batch_id,12)} <Icon name="copy" size={13}/></button></div><div className="availability"><span>可用 {fmt(Number(h.quantity)-Number(h.locked_quantity))}</span><div><i style={{width:`${Number(h.quantity)?(Number(h.quantity)-Number(h.locked_quantity))/Number(h.quantity)*100:0}%`}}/></div><small>锁定 {fmt(h.locked_quantity)}</small></div></div>})}</div>:<Empty title="暂无碳资产" text="额度签发或市场购买完成后，资产将显示在这里。"/>}</div>
      <div className="card"><div className="card-head"><div><span className="eyebrow">LEDGER</span><h3>资产流水</h3></div></div>{ledger.length?<><div className="timeline">{ledger.map(l=><div key={l.id}><span className={`flow-dot ${Number(l.quantity_delta)>=0?'in':'out'}`}>{Number(l.quantity_delta)>=0?'+':'−'}</span><div><strong>{{issue:'额度签发',trade_in:'市场买入',trade_out:'市场卖出',retire:'永久注销'}[l.kind]||l.kind}</strong><small>{date(l.created_at)} · {short(l.batch_id,6)}</small></div><b className={Number(l.quantity_delta)>=0?'positive':'negative'}>{Number(l.quantity_delta)>0?'+':''}{fmt(l.quantity_delta)} t</b></div>)}</div><Pagination page={ledgerPage} total={ledgerResult.total} pageSize={PAGE_SIZE} onChange={setLedgerPage}/></>:<Empty title="暂无资产流水" text="资产发生变化时会留下完整记录。"/>}</div></section>
  </>
}

export { MarketPage } from './market'

export function RetirementsPage({user,notify}:{user:User;notify:(m:string,t?:'success'|'error')=>void}){
  const [modal,setModal]=useState(false),[query,setQuery]=useState(''),[found,setFound]=useState<Retirement|null>(null),[page,setPage]=useState(0)
  const [recordResult,loading,reload]=useLoad(()=>requestPage<Retirement[]>(`/retirements?limit=9&offset=${page*9}`),{data:[],total:0},[page]),records=recordResult.data,[holdings]=useLoad(()=>request<Holding[]>('/wallet/holdings'),[]),[batches]=useLoad(()=>request<Batch[]>('/credits/batches?limit=100'),[]),[chain]=useLoad(()=>request<ChainConfig>('/chain/config'),{enabled:false,network:'',chain_id:0,confirmations:1})
  const retire=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={batch_id:field(f,'batch_id'),quantity:field(f,'quantity'),beneficiary:field(f,'beneficiary'),reason:field(f,'reason')};try{let r:Retirement;if(chain.enabled){const batch=batches.find(b=>b.id===payload.batch_id);if(!batch?.chain_batch_id)throw new Error('该批次尚未完成链上签发');const {credits}=await wallet(user);const tx=await credits.retire(batch.chain_batch_id,creditAmount(payload.quantity),keccak256(toUtf8Bytes(payload.beneficiary)),keccak256(toUtf8Bytes(payload.reason)));notify('注销交易已签名，正在等待链上确认');const receipt=await tx.wait(chain.confirmations);r=await request<Retirement>('/retirements/confirm',json({...payload,transaction_hash:receipt.hash}))}else{r=await request<Retirement>('/retirements',{...json(payload),headers:{'Idempotency-Key':idempotencyKey()}})}notify(`注销完成，证书 ${r.certificate_no}`);setModal(false);reload()}catch(error){notify(error instanceof Error?error.message:'注销失败','error')}}
  const verify=()=>{if(!query)return;request<Retirement>(`/retirements/${encodeURIComponent(query)}`).then(setFound).catch(e=>{setFound(null);notify(e.message,'error')})}
  return <><PageIntro eyebrow="RETIREMENT" title="永久注销与凭证" text="将碳额度永久移出流通，生成可公开验证的唯一凭证。"><button className="btn btn-primary" onClick={()=>setModal(true)} disabled={!holdings.some(h=>Number(h.quantity)>Number(h.locked_quantity))}><Icon name="retire"/>发起注销</button></PageIntro>
    <section className="certificate-search"><div><Icon name="search"/><div><strong>验证注销证书</strong><span>输入证书编号，公开核验注销记录</span></div></div><div className="search-box"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&verify()} placeholder="CLR-2026…"/><button onClick={verify}>立即验证</button></div></section>
    {found&&<div className="verified-banner"><span><Icon name="check"/></span><div><b>证书真实有效</b><small>{found.certificate_no} · {found.beneficiary} · {fmt(found.quantity)} tCO₂e</small></div><button onClick={()=>setFound(null)}><Icon name="close"/></button></div>}
    <div className="card"><div className="card-head"><div><span className="eyebrow">CERTIFICATES</span><h3>我的注销凭证</h3></div><span className="result-count">{recordResult.total} 张证书</span></div>{loading?<Loader/>:records.length?<><div className="certificate-grid">{records.map(r=><article className="certificate" key={r.id}><div className="cert-watermark"><Icon name="leaf" size={80}/></div><header><span className="cert-seal"><Icon name="check"/></span><span>VERIFIED RETIREMENT</span></header><h3>{fmt(r.quantity)} <small>tCO₂e</small></h3><p>已代表 <b>{r.beneficiary}</b> 永久注销</p><div className="cert-line"/><footer><div><span>证书编号</span><b>{r.certificate_no}</b></div><div><span>注销时间</span><b>{date(r.retired_at)}</b></div></footer></article>)}</div><Pagination page={page} total={recordResult.total} pageSize={9} onChange={setPage}/></>:<Empty title="暂无注销凭证" text="注销碳额度后，具有唯一编号的凭证将显示在这里。"/>}</div>
    {modal&&<Modal title="发起碳额度注销" onClose={()=>setModal(false)}><form className="form-grid" onSubmit={retire}><div className="form-note warning full">注销不可撤销；启用链上模式时，必须由资产持有人的钱包亲自签名。</div><label className="full">资产批次<select name="batch_id">{holdings.filter(h=>Number(h.quantity)>Number(h.locked_quantity)).map(h=><option value={h.batch_id} key={h.batch_id}>{short(h.batch_id,12)} · 可用 {fmt(Number(h.quantity)-Number(h.locked_quantity))} t</option>)}</select></label><label>注销数量（tCO₂e）<input name="quantity" type="number" step="0.0001" min="0.0001" required/></label><label>受益方<input name="beneficiary" required placeholder="企业或项目名称"/></label><label className="full">注销用途<textarea name="reason" rows={3} required placeholder="例如：2026 年运营排放抵消"/></label><FormActions close={()=>setModal(false)} submit={chain.enabled?'连接钱包并签名注销':'确认永久注销'}/></form></Modal>}
  </>
}

export function BlockchainPage(){
  const [page,setPage]=useState(0),[config,loading]=useLoad(()=>request<BlockchainConfig>('/system/blockchain'),null as BlockchainConfig|null),[opResult]=useLoad(()=>requestPage<ChainOperation[]>(`/system/blockchain/operations?limit=${PAGE_SIZE}&offset=${page*PAGE_SIZE}`),{data:[],total:0},[page]),ops=opResult.data
  if(loading||!config)return <Loader/>
  return <><PageIntro eyebrow="ON-CHAIN ANCHORING" title="链上存证" text="监控网络配置、智能合约与业务存证任务。"/>
    <section className="chain-overview"><div className="chain-network"><span className="chain-logo">A</span><div><span>当前网络</span><strong>{config.network}</strong><small>Chain ID · {config.chain_id}</small></div><Status value={config.enabled&&config.configured?'confirmed':'failed'}/></div><div><span>确认区块数</span><strong>{config.confirmations}</strong><small>笔交易确认阈值</small></div><div><span>签名方式</span><strong>{config.signing_mode==='external_signer'?'外部签名服务':config.signing_mode==='local_signer'?'本地签名':'未配置'}</strong><small>敏感凭证不会在此显示</small></div></section>
    <div className="card contract-card"><div className="card-head"><div><span className="eyebrow">SMART CONTRACTS</span><h3>合约配置</h3></div></div><div className="contract-rows"><div><span className="contract-icon"><Icon name="project"/></span><div><b>项目登记合约</b><code>{config.project_contract_address||'尚未配置'}</code></div></div><div><span className="contract-icon"><Icon name="wallet"/></span><div><b>碳积分账本合约</b><code>{config.credit_contract_address||'尚未配置'}</code></div></div><div><span className="contract-icon"><Icon name="market"/></span><div><b>碳积分 / USDC 市场合约</b><code>{config.marketplace_contract_address||'尚未配置'}</code></div></div><div><span className="contract-icon"><Icon name="wallet"/></span><div><b>USDC 结算合约</b><code>{config.usdc_contract_address||'尚未配置'}</code></div></div><div><span className="contract-icon"><Icon name="chain"/></span><div><b>审批操作账户</b><code>{config.operator_address||'尚未配置'}</code></div></div></div></div>
    <div className="card"><div className="card-head"><div><span className="eyebrow">OUTBOX</span><h3>链上任务队列</h3></div><span className="result-count">{opResult.total} 项任务</span></div>{ops.length?<><div className="table-wrap"><table><thead><tr><th>任务类型</th><th>业务资源</th><th>合约</th><th>状态</th><th>尝试</th><th>交易哈希</th><th>创建时间</th></tr></thead><tbody>{ops.map(o=><tr key={o.id}><td><strong>{{'project.register':'项目登记','credit.issue':'额度签发','credit.retire':'额度注销'}[o.operation_type]||o.operation_type}</strong></td><td>{o.resource_type} · {short(o.resource_id,6)}</td><td><code>{short(o.contract_address,8)}</code></td><td><Status value={o.status}/></td><td>{o.attempts}</td><td><code>{o.transaction_hash?short(o.transaction_hash,10):'—'}</code></td><td>{date(o.created_at)}</td></tr>)}</tbody></table></div><Pagination page={page} total={opResult.total} pageSize={PAGE_SIZE} onChange={setPage}/></>:<Empty title="链上队列为空" text="项目核证、额度签发或注销后，待存证任务会显示在这里。"/>}</div>
    <div className="info-banner"><Icon name="chain"/><div><b>审批与资产处分权已分离</b><span>平台只为审核通过的项目提交登记和签发交易；用户钱包独立签署挂单、购买、撤单与注销，资产余额以链上合约为准。</span></div></div>
  </>
}

export function AuditPage(){
  const [page,setPage]=useState(0),[eventResult,loading]=useLoad(()=>requestPage<AuditEvent[]>(`/system/audit-events?limit=${PAGE_SIZE}&offset=${page*PAGE_SIZE}`),{data:[],total:0},[page]),events=eventResult.data,[search,setSearch]=useState('')
  const shown=events.filter(e=>`${e.action} ${e.resource_type} ${e.resource_id}`.toLowerCase().includes(search.toLowerCase()))
  const labels:Record<string,string>={'user.registered':'用户注册','project.created':'创建项目','project.submitted':'提交项目','project.reviewed':'审核项目','credits.issued':'签发额度','listing.created':'发布挂单','listing.cancelled':'撤销挂单','trade.settled':'交易结算','credits.retired':'额度注销'}
  return <><PageIntro eyebrow="AUDIT TRAIL" title="审计日志" text="查看关键业务行为与操作者，满足内控和追溯要求。"/>
    <div className="toolbar"><div className="search"><Icon name="search" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索操作或资源编号"/></div><span className="result-count">最近 {shown.length} 条记录</span></div>
    <div className="card table-card">{loading?<Loader/>:shown.length?<><div className="audit-list">{shown.map(e=><div className="audit-row" key={e.id}><span className="audit-node"><Icon name="audit" size={17}/></span><div className="audit-main"><strong>{labels[e.action]||e.action}</strong><span>{e.resource_type} · {short(e.resource_id,10)}</span></div><code>{e.actor_id?short(e.actor_id,7):'SYSTEM'}</code><time>{date(e.created_at)}</time></div>)}</div><Pagination page={page} total={eventResult.total} pageSize={PAGE_SIZE} onChange={setPage}/></>:<Empty title="没有匹配的日志" text="换一个关键词重新搜索。"/>}</div>
  </>
}

function PageIntro({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children?:React.ReactNode}){return <section className="page-intro"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>{children&&<div>{children}</div>}</section>}
function FormActions({close,submit}:{close:()=>void;submit:string}){return <div className="form-actions full"><button type="button" className="btn btn-ghost" onClick={close}>取消</button><button className="btn btn-primary" type="submit">{submit}</button></div>}
